"""Api requests table

Revision ID: 1eb34e97473d
Revises: 952732aefde9
Create Date: 2020-06-19 14:51:01.532383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb34e97473d'
down_revision = '952732aefde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_requests')
    # ### end Alembic commands ###
