"""Deleted synonyms in Word

Revision ID: 2e68dca228c4
Revises: 46a4a8ae9d90
Create Date: 2020-05-03 14:18:54.104756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e68dca228c4'
down_revision = '46a4a8ae9d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'synonyms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('synonyms', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
