"""Date completed in Statistic table

Revision ID: 3dd4e1b146cf
Revises: 66148d85dd36
Create Date: 2020-04-11 19:16:47.087610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dd4e1b146cf'
down_revision = '66148d85dd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.drop_column('statistic', 'game_finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('game_finished', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('statistic', 'date_completed')
    # ### end Alembic commands ###
