"""Removed useless fields in CurrentGame table

Revision ID: 40f57f558217
Revises: 956e45931fad
Create Date: 2020-04-26 14:46:44.728574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40f57f558217'
down_revision = '956e45931fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_game', 'game_date_completed')
    op.drop_column('current_game', 'game_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('game_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('current_game', sa.Column('game_date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
