"""Selected synonyms for word in separate table

Revision ID: 46a4a8ae9d90
Revises: f08e0430cb4f
Create Date: 2020-05-03 12:31:11.586147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a4a8ae9d90'
down_revision = 'f08e0430cb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('synonym', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_synonyms')
    # ### end Alembic commands ###
