"""Init db

Revision ID: 48f08ded7fde
Revises: 
Create Date: 2020-04-18 20:14:44.130992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f08ded7fde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=250), nullable=True),
    sa.Column('definition', sa.String(length=550), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_definitions_spelling'), 'definitions', ['spelling'], unique=False)
    op.create_table('synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=250), nullable=True),
    sa.Column('synonym', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_spelling'), 'synonyms', ['spelling'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('secret_question', sa.String(length=128), nullable=True),
    sa.Column('secret_answer_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('current_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date_started', sa.DateTime(), nullable=True),
    sa.Column('game_date_completed', sa.DateTime(), nullable=True),
    sa.Column('game_completed', sa.Boolean(), nullable=True),
    sa.Column('game_type', sa.String(length=30), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=30), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.String(length=550), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_index')
    op.drop_table('words')
    op.drop_table('statistic')
    op.drop_table('dictionaries')
    op.drop_table('current_game')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_synonyms_spelling'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_definitions_spelling'), table_name='definitions')
    op.drop_table('definitions')
    # ### end Alembic commands ###
