"""Spelling in Definitions table

Revision ID: 4b2f802f2f06
Revises: 6e5f282c2a40
Create Date: 2020-03-22 16:25:52.662139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2f802f2f06'
down_revision = '6e5f282c2a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('spelling', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_definitions_spelling'), 'definitions', ['spelling'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_definitions_spelling'), table_name='definitions')
    op.drop_column('definitions', 'spelling')
    # ### end Alembic commands ###
