"""Synonyms in words table

Revision ID: 956e45931fad
Revises: 48f08ded7fde
Create Date: 2020-04-25 11:02:15.571960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956e45931fad'
down_revision = '48f08ded7fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('synonyms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'synonyms')
    # ### end Alembic commands ###
