"""Removed word_id from Definition table

Revision ID: a786682c6770
Revises: 4b2f802f2f06
Create Date: 2020-03-30 21:25:43.414047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a786682c6770'
down_revision = '4b2f802f2f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('definitions_word_id_fkey', 'definitions', type_='foreignkey')
    op.drop_column('definitions', 'word_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('definitions_word_id_fkey', 'definitions', 'words', ['word_id'], ['id'])
    # ### end Alembic commands ###
