"""Synonyms table for WordApi

Revision ID: d45a8ff8dfbf
Revises: a786682c6770
Create Date: 2020-04-07 21:10:15.330811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45a8ff8dfbf'
down_revision = 'a786682c6770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synonyms', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('synonyms', sa.Column('spelling', sa.String(length=250), nullable=True))
    op.add_column('synonyms', sa.Column('synonym', sa.String(length=550), nullable=True))
    op.create_index(op.f('ix_synonyms_spelling'), 'synonyms', ['spelling'], unique=False)
    op.drop_constraint('synonyms_synonym_id_fkey', 'synonyms', type_='foreignkey')
    op.drop_constraint('synonyms_word_id_fkey', 'synonyms', type_='foreignkey')
    op.drop_column('synonyms', 'word_id')
    op.drop_column('synonyms', 'synonym_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synonyms', sa.Column('synonym_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('synonyms', sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('synonyms_word_id_fkey', 'synonyms', 'words', ['word_id'], ['id'])
    op.create_foreign_key('synonyms_synonym_id_fkey', 'synonyms', 'words', ['synonym_id'], ['id'])
    op.drop_index(op.f('ix_synonyms_spelling'), table_name='synonyms')
    op.drop_column('synonyms', 'synonym')
    op.drop_column('synonyms', 'spelling')
    op.drop_column('synonyms', 'id')
    # ### end Alembic commands ###
