"""Synonyms table for WordApi

Revision ID: e96e2c7c5fb4
Revises: fd0edef54910
Create Date: 2020-04-08 18:58:02.717669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96e2c7c5fb4'
down_revision = 'fd0edef54910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=250), nullable=True),
    sa.Column('synonym', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_spelling'), 'synonyms', ['spelling'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synonyms_spelling'), table_name='synonyms')
    op.drop_table('synonyms')
    # ### end Alembic commands ###
