"""Game rounds in separate table

Revision ID: f08e0430cb4f
Revises: 40f57f558217
Create Date: 2020-05-03 12:07:38.259195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08e0430cb4f'
down_revision = '40f57f558217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('current_game_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=550), nullable=True),
    sa.Column('correct_answer', sa.String(length=550), nullable=True),
    sa.Column('answer0', sa.String(length=550), nullable=True),
    sa.Column('answer1', sa.String(length=550), nullable=True),
    sa.Column('answer2', sa.String(length=550), nullable=True),
    sa.Column('answer3', sa.String(length=550), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_game_id'], ['current_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_round_order'), 'game_round', ['order'], unique=False)
    op.drop_column('current_game', 'game_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('game_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_game_round_order'), table_name='game_round')
    op.drop_table('game_round')
    # ### end Alembic commands ###
