"""Synonyms table for WordApi

Revision ID: fd0edef54910
Revises: d45a8ff8dfbf
Create Date: 2020-04-08 18:56:32.756612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0edef54910'
down_revision = 'd45a8ff8dfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonyms1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=250), nullable=True),
    sa.Column('synonym', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms1_spelling'), 'synonyms1', ['spelling'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synonyms1_spelling'), table_name='synonyms1')
    op.drop_table('synonyms1')
    # ### end Alembic commands ###
